name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]  # atualiza todos os dias à meia-noite UTC
  push: {branches: ["main"]}
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_achievements: yes
          plugin_lines: yes
          plugin_followup: yes
